### ISSUE TITLE
HashMD v2 Roadmap

### ISSUE THREAD

**Issue by pd4d10** [pd4d10/hashmd#271]
## Major changes

- [ ] CodeMirror v5 -> v6
- [ ] Svelte -> Web Components, also with popular frameworks wrapper
- [ ] Sanitize improvement #131
- [ ] CSS: `inline-block` -> flexbox
- [ ] Deprecate UMD bundle in favor of ESM
- [ ] Controlled mode #242
- [ ] Make ToC accessible #324
- [ ] Built-in dark mode #40 
- [ ] Support RTL languages #265

**Comment by ZachSaucier** [comment]
I'd love to see "Controlled mode". Are you open to PRs?

**Comment by classfang** [comment]
现在还在开发吗？还是停止维护了？

**Comment by yoruxyy** [comment]
Have you stopped maintenance?

**Comment by tofrankie** [comment]
不维护了吗？ 👀
